### ISSUE TITLE
Rework plugins

### ISSUE THREAD

**Issue by olov** [olov/ng-annotate#111]
The plugin API is super-experimental haven't been kept up to date. The API as it once was created focused a lot on extensibility it terms of matching rather than providing usable output for other tools (the latter is probably more useful).

The API as it looks right now should most likely be deprecated in favor of a new, improved (and documented) API. I welcome contributions in this area!

**Comment by vatula** [comment]
I found it almost okay. The usage of custom attributes on nodes like $chained etc is  obscure though and I still don't understand what needs to be returned by the plugin. A function that needs guards?

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
