### ISSUE TITLE
ngAnnotate does not annotate ui-router routes.

### ISSUE THREAD

**Issue by sayakb** [olov/ng-annotate#125]
First of all, thanks for this awesome plugin!

I have the following code to dynamically resolve controller / view names:

```
app.config(function ($stateProvider, $urlRouterProvider) {
    $stateProvider.state('default', angularAMD.route({
        url: '/:module/:action',

        templateUrl: function (params) {
            var folderName = params.module;
            var fileName = params.module + params.action.charAt(0).toUpperCase() + params.action.substr(1);

            return 'app/views/' + folderName + '/' + fileName + 'View.html';
        },

        resolve: {
            loadController: function ($q, $stateParams) {
                var controllerName = $stateParams.module + 'Controller';
                var deferred = $q.defer();

                require([controllerName], function () {
                    deferred.resolve();
                });

                return deferred.promise;
            }
        },

        controllerProvider: function ($stateParams) {
            return $stateParams.module + 'Controller';
        },
    }));
});
```

When I run ngAnnotate, `loadController` and `controllerProvider` are not annotated. For now, I'm adding an /* @ngInject */ tag on top of them, but it'll be awesome if ngAnnotate supported them.

**Comment by olov** [comment]
Hello! ng-annotate does support `$stateProvider.state` in it's generic form. Your example does not work because of the `angularAMD.route` function wrapper and unfortunately that's not going to change because slipperly slope and static analysis of a dynamic language. `ngInject` is your friend!
