### ISSUE TITLE
Setting value on a const breaks es6 (and consequently, iojs)

### ISSUE THREAD

**Issue by kentcdodds** [olov/ng-annotate#126]
You have [these lines](https://github.com/olov/ng-annotate/blob/master/ng-annotate-main.js#L285-L290) in the `matchProvide` function.

```js
const target = obj.type === "Identifier" && obj.name === "$provide" &&
is.someof(method.name, ["decorator", "service", "factory", "provider"]) &&
args.length === 2 && args[1];

if (target) {
  target.$methodName = method.name;
```

You can't set the property of a constant. Now that iojs executes in an es6 context, this is failing.

**Comment by olov** [comment]
You absolutely can set the property of a `const`. `const` means the the name binding can't be changed but says nothing about deep immutability.

This is my guess: You are running 0.15.0 and have problems, but you're looking at recent source code. 0.15.1 was released an hour later or so. In 0.15.0, the `if (target)` guard is missing and `target.$methodName` is assigned unconditionally, even if `target` is `false`. This is not allowed per ES5 strict mode, but old versions of v8 (those in node) didn't complain while new versions of v8 (that in io.js) throws. It's not related to ES6 though.

If you are running 0.15.1 and are having problems then please paste the stack trace here. Thanks!

**Comment by olov** [comment]
..and reopen in that case

**Comment by kentcdodds** [comment]
Works if I use 0.15.1, I'm using `gulp-ng-annotate`. I'll ask them to update their dependency.

**Comment by olov** [comment]
Tools that depend on ng-annotate, such as gulp-ng-annotate generally does it with the `~` operator so patch releases will flow through automatically. Just reinstall gulp-ng-annotate and you should be fine.
