### ISSUE TITLE
Add custom styles

### ISSUE THREAD

**Issue by kentcdodds** [olov/ng-annotate#127]
So, I'm refactoring my project to use CommonJS and trying to make things more modular. So all of my components have the module passed to them and they register with that module. Like so:

```js
module.exports = ngModule => {
  ngModule.directive('myDirective', function($log) {
    return function link() {
      $log.info('linking!', arguments);
    }
  });
}
```

I'd like to have the ability to add a custom style that says: "My `angular.module` is actually `ngModule`" I'm fine with sticking with `ngModule` for everything. Just want it to be a variable.

**Comment by kentcdodds** [comment]
Sorry, pressed ⌘+Enter too soon. Updated.

**Comment by olov** [comment]
Let's see if I understand you correctly.. ng-annotate will by default consider `ngModule.directive` valid just as well as `angular.module("myMod).directive`. We call this a "short form", see https://github.com/olov/ng-annotate#declaration-forms for more info about it and how you can restrict matching to only identifiers matching a certain pattern using the `--regexp` option. If you use a ng-annotate wrapper then you need to check what its default options are. Did that answer your question?

**Comment by kentcdodds** [comment]
Another example of something that I do a lot:

```js
ngModule.directive('myDirective', myDirective);

function myDirective() {}
```

**Comment by kentcdodds** [comment]
Let me look into that. I'll let you know. I didn't know about the regexp option. Thanks

**Comment by kentcdodds** [comment]
Oh, looks like ng-annotate is working just fine without the `--regexp` option. For some reason I thought it wasn't working. Thanks again for this awesome module!

**Comment by olov** [comment]
Great!
