### ISSUE TITLE
"ngInject" should prefer .$inject arrays over inline arrays

### ISSUE THREAD

**Issue by olov** [olov/ng-annotate#132]
```js
class C {
  constructor($scope) {
    "ngInject"
  }
}
```

is transformed by Traceur into

```js
$traceurRuntime.ModuleStore.getAnonymousModule(function() {
  "use strict";
  var C = function C($scope) {
    "ngInject";
  };
  ($traceurRuntime.createClass)(C, {}, {});
  return {};
});
```

and ng-annotate currently changes C from a function to an array, so Traceur bails.

Due for 0.16

Also #124

cc @andreasgrimm

**Comment by andreasgrimm** [comment]
Out of curiosity, would this be a special case just for class constructors where the `.$inject` style would be prefered over the array inline style or rather something like a global option?

What about being able to choose the inject style per usage of ngInject? maybe something like `"ngInjectI"` vs. `"ngInjectA"` .. or just an additional `"ngInjectI"` for the inline style? .. just throwing in some thoughts though :)

**Comment by olov** [comment]
This would most likely be applied everywhere (no option). Bound functions would get an $inject-array, inline functions would get an inline array. I don't think users should be able to opt-in via ngInject because a similar situation is anyway happening in matched targets. Hopefully we can continue making ng-annotate just work(TM), with the occassional ngInject here and there. :-)

**Comment by andreasgrimm** [comment]
ok, sounds great.

If you need a test scenario, I just released an AngularJS-jspm seed/example. This uses es6 classes for controllers and services almost throughout. It works fine after jspm bundling but yet without application of ng-annotate / uglify (what it did in the past using the `ngInject(..)` helper function and without usage of classes but instead conventional contructor functions).

As soon as there's a verion of ng-annotate that can handle es6 classes, running the gulp task `production` should then produce a working system again.

It's here: https://github.com/ng-next/ng-next-example  (and still has some rough edges ;) )

**Comment by olov** [comment]
Fixed in 0.15.4. `"ngInject"`-prologued functions will now be annotated with `fn.$inject = [..]` when possible, i.e. when fn is a function declaration or when fn is a function expression that's the rhs of a variable declaration.

**Comment by andreasgrimm** [comment]
awesome. now es6 classes are working :)
thanks a ton!

**Comment by olov** [comment]
Glad you liked it!
