### ISSUE TITLE
Duplicate injection annotation added

### ISSUE THREAD

**Issue by rcollette** [olov/ng-annotate#135]
I have annotated and angular service with /*@ngInject*/ but it is resulting in two assignmets to FuntionName.$inject

See input and out files here:
https://drive.google.com/folderview?id=0Bx7rOpBwQPKgflhkNFdRZjFiQXJBZUdEMmVNdko2MWZsaDJ6bkpUekJYNVE0ODFVMnF4Y2M&usp=sharing

**Comment by olov** [comment]
Confirmed. Thanks for reporting. This should not happen and will get fixed in next release. For now you can just remove the `/*@ngInject*/ and ng-annotate will match it anyways.
