### ISSUE TITLE
support io.js

### ISSUE THREAD

**Issue by atian25** [olov/ng-annotate#136]
change to `io.js` got error:

> Cannot assign to read only property '$methodName' of false

**Comment by omsmith** [comment]
Seems to be a dupe of #126 

Make sure you're running the latest version of _ng-annotate_

**Comment by olov** [comment]
Yup. @omsmith thanks for being so active in the issues. I flipped your collaborator bit - try it out by closing this one! =)

**Comment by atian25** [comment]
sorry, 3x~
