### ISSUE TITLE
Reference not found when the var is declared empty and defined later.

### ISSUE THREAD

**Issue by acroca** [olov/ng-annotate#138]
The following code doesn't get annotated:
```
var MyCtrl;
MyCtrl = function(a, b) {
}
angular.module("MyMod").controller("foo", MyCtrl);
```

This is actually how Coffeescript generates code.

**Comment by acroca** [comment]
Found #90, closing this one.

**Comment by acroca** [comment]
Actually the syntax in #108 and this one is quite different.

**Comment by olov** [comment]
Hi! I don't plan to add support for this, mainly because I'm concerned that it will increase the risk of false positives. ngInject is your friend here, try:

```coffeescript
MyCtrl = (a, b) ->
  "ngInject";
  foobar

angular.module("MyMod").controller("foo", MyCtrl);
```

**Comment by acroca** [comment]
Ok, no problem. Thanks
