### ISSUE TITLE
How to use ng-strict-di in development

### ISSUE THREAD

**Issue by lvarayut** [olov/ng-annotate#142]
I just get started using the `ng-annotate`. I use `grunt-ng-annotate` to add annotations before minifying files. It worked perfectly. However, in the development environment, I got an error because I'm using `ng-strict-di`. 

I have read your guide and you [highly recommend enabling ng-strict-di in your minified builds](https://github.com/olov/ng-annotate#highly-recommended-enable-ng-strict-di-in-your-minified-builds). In my app, I manually add `ng-strict-di` when initializing the app:

```javascript
    angular.bootstrap(document, ['sms'], {
    	strictDi: true
    });
```

So, I defined controllers without any angular annotation, for example,

```javascript
    angular
        .module('sms.budgets')
        .controller('BudgetsGraphController', BudgetGraph);
   
     /*@ngInject*/ 
    function BudgetGraph(Global, Budgets, Transactions, AcademicYear) {
         ....
    }
```

Is there anyway I can get rid of this error? What I can think of is to disable the `ng-strict-di` mode during the development and have some way to add it in the minified build. However, I don't know exactly how to do it. Any help would be really appreciated.

**Comment by olov** [comment]
You're on the right track. You need to conditionally include that strictDi line or at least adjust its boolean value, depending on dev/prod build. I'm not a grunt user myself but a quick search gave this: https://github.com/jsoverson/grunt-preprocess . Perhaps @mzgol knows if there's a more popular grunt way to accomplish this?

**Comment by mzgol** [comment]
I apply this setting everywhere and use it in development as well. I author files with non-strict annotation but I preprocess them even in development before sending them to the browser.

Setting `ng-strict-di` just in production doesn't buy you much - the error message is unreadable either way. IMO the whole point of `ng-strict-di` is to set it in unminified files as well so that you can spot the problem immediately in a source you can understand.

**Comment by omsmith** [comment]
:+1: to what @mzgol said.

Minify in dev, minify in unit tests, minify everywhere. It really sucks when something has been working but then doesn't in your tests, or doesn't once you deploy. Keep the environment consistent.

Enable sourcemaps in dev if needed.

**Comment by olov** [comment]
That's excellent advice @mzgol and @omsmith. Include ng-annotate in your development builds if your build system allows for it. If it doesn't then do something similar to https://github.com/olov/ng-annotate/issues/142#issuecomment-75056072 but be prepared that if something breaks then you'll need to turn off minification anyways to make sense of the ng-strict-di error message.

**Comment by lvarayut** [comment]
@olov, @mzgol, @omsmith, Thanks for the great advices. 

@olov, I will take a look at it. :+1: 

@mzgol, If I understand correctly, you use `grunt-ng-annotate` to read all the javascript files, add annotations, and write to another files, might be `*.annotate.js`. Then, these `*.annotate.js` would be used in development instead of your normal javascript files. Am I right?

@omsmith, I see your point. So, you use minified files in your development. Does it take too much time to compile when some files are changed? When there are some errors, Is it not difficult to debug your code?

**Comment by mzgol** [comment]
> @mzgol, If I understand correctly, you use grunt-ng-annotate to read all the javascript files, add annotations, and write to another files, might be *.annotate.js. Then, these *.annotate.js would be used in development instead of your normal javascript files. Am I right?

Yup.

**Comment by omsmith** [comment]
@lvarayut I use [browserify](https://github.com/substack/node-browserify) and [watchify](https://github.com/substack/watchify) for build and development. With output caching, updates take no time at all - although ng-annotate is very fast at what it is, and starting fresh doesn't take very long at all.

When using browserify's and ng-annotate's sourcemap support, debugging is very simple, as the browser is given the mappings to expose the source files as they were originally

**Comment by lvarayut** [comment]
@olov, @omsmith, Thanks again for your response. It sounds good to me. I will give it a try.
