### ISSUE TITLE
Configure annotation of file exporting controller function

### ISSUE THREAD

**Issue by kentcdodds** [olov/ng-annotate#144]
Is there any way to make ng-annotate recognize my controller functions as injectable without using the comment? An example would be:

```javascript
module.exports = SomeCtrl;
function SomeCtrl($log) {
}
```

All files have the name `controller.js` and they can contain more than just the `SomeCtrl` function, but the `SomeCtrl` is the only `module.exports`.

**Comment by olov** [comment]
You'll need to use an explicit ngInject annotation for this but not necessarily as a comment. Try this:

```javascript
function SomeCtrl($log) {
    "ngInject";
}
```

**Comment by kentcdodds** [comment]
I don't mind the comment, I was just hoping that I could get away with not having to do extra work and just teach ng-annotate my convention. If that's not possible then that's fine.
