### ISSUE TITLE
Add support for flux-angular

### ISSUE THREAD

**Issue by jrust** [olov/ng-annotate#145]
The [flux-angular](https://github.com/christianalfoni/flux-angular) project adds `.store` as another type of provider.  e.g.:
```
angular.module('app', ['flux']).store('MyStore', function () { 
});
```

Is it possible to add support for this?  If not, is it something that can be accomplished with the regex option?

**Comment by olov** [comment]
Sure - I'll add it to the next release. regexp won't help you in the meantime but ngInject will.

**Comment by szimek** [comment]
+1. I've just spend an hour trying to figure out why all our tests (which run minified code) fail. Since we'd switched from ng-min to ng-annotate we never had any problems with annotations (thank you so much for that!), so I totally forgot that it can actually be the problem :)

**Comment by olov** [comment]
@szimek glad to hear that it's been working mostly well for you! make sure that you have ng-strict-di enabled to reduce the pain of any future problems: https://github.com/olov/ng-annotate#highly-recommended-enable-ng-strict-di-in-your-minified-builds
