### ISSUE TITLE
Teach ng-annotate about new pattern

### ISSUE THREAD

**Issue by Rush** [olov/ng-annotate#149]
I have my own service which internally calls upon the `$injector` service to resolve dependencies for a function, how I use it is:
```js
$hook.register('UserCtrl', /*@ngInject*/ function($scope, billingService) {
  // something
});
```

Is there a way to dynamically teach ng-annotate about this pattern? I thought regexp would do it but it seems it's totally for something else.

Thank you!

**Comment by olov** [comment]
The recommended way is to use ngInject. Alternatively, you can try creating a plugin but beware that the API is still experimental and there's not much in terms of documentation. https://github.com/olov/ng-annotate#installation-and-usage is a starting point.
