### ISSUE TITLE
Work for resolves everywhere?

### ISSUE THREAD

**Issue by eddiemonge** [olov/ng-annotate#150]
I have a custom directive that accepts a resolve like ngRoute and ui-router provide but doesn't get annotated

```coffeescript
Modal.open 'modal',
  templateUrl: '/templates/sharing.html'
  controller: 'SharingController'
  resolve:
    Permissions: [ 'API', ( API ) ->
      API.query file_id: file.id
    ]
```

**Comment by olov** [comment]
Right, ng-annotate doesn't know about your custom directive so it doesn't annotate it.

You have three options:
 1. (recommended) use `ngInject`
 2. mimic ui-router API exactly i.e. `$modal.open({.. controller: fn, resolve: {f: function($scope) {}, ..}});` 
 3. write a plugin (but beware that plugin API is experimental and there is not much documentation, see README).
