### ISSUE TITLE
ngAnnotate does not seem to prevent angular.bootstrap from breaking after minification

### ISSUE THREAD

**Issue by jrgleason** [olov/ng-annotate#151]
I am working on a pretty complex Angular app that requires multiple route providers on the page at the same time. In order to accomplish this I have been using multiple modules then wiring them up with 'angular.bootstrap'. However, when I mangle the js (after ng-annotate) using uglify I get a lost provider. 

My current workaround is to turn off mangling but I would like to avoid that.

More info...
http://stackoverflow.com/questions/29302789/angular-bootstrap-seems-to-break-when-uglyfied

**Comment by olov** [comment]
Please create a minimal example and provide the actual ng-annotate output as well as the expected output. Install ng-annotate with `npm install -g ng-annotate` and then run `ng-annotate -a example.js` to get the actual output.

**Comment by jrgleason** [comment]
So this might be where things get a little hairy, how about this... 

I will create a simple plnkr so you can see what I am doing. Then when I get home tonight I will make it minify. I think once you see what I am doing something might click.

http://plnkr.co/edit/8kfT0W8cyAhH0OS7b3Kz?p=preview

**Comment by olov** [comment]
I need the data I requested in my previous comment to be able to provide you further feedback on this.

**Comment by jrgleason** [comment]
Sure I will try to get that as soon as possible. Seems strange though my first shot at getting it to fail in plunker did not work so let me revisit and I will post the annotated as well as minified file later. In the meantime I will try upgrading and see if that helps

**Comment by jrgleason** [comment]
I could also send you my full prod JS files but I would not want to post those here :-)

**Comment by olov** [comment]
Please don't provide the minified file, I don't want to see it to be honest. I need you to figure out how you would have liked ng-annotate to transform your code and how it did transform it (on a small snippet). If you can't figure this out then please find a sponsor that can help you with it, because I just don't have the bandwidth for more generic kind of free support.

**Comment by jrgleason** [comment]
No that's fine I can do it just take some time

**Comment by jrgleason** [comment]
So this looks to be related to having 2 Controllers with the same name I had...

    //Old Should have been removed
    var NavbarController = function ($scope) {
      
    };
    DrawerDirective = function () {
      return {
        controller: NavbarController,
        controllerAs: 'nc',
        ....
      }
    };
    uiModule
        .directive('njNavbar', DrawerDirective);
    //New Should have been used...
    function NavbarController($scope, $window) {
       ...   
    }
    navbarApp
        .controller('navbarController', NavbarController);
    

I will again try and come up with an example and post it later.

I am not sure if this is an issue you would want to fix. My solution was to refactor since I didn't need the other directive anymore. Especially in ng2 I would think this would happen some. 

Thanks for trying to help!

**Comment by olov** [comment]
Closing (need more info)
