### ISSUE TITLE
Underscores _.filter breaks annotation

### ISSUE THREAD

**Issue by philippfrank** [olov/ng-annotate#155]
```coffee
$scope.filtered = (collection) ->
  _.filter collection, foo: "bar"
```

This breaks the build. Obviously ng-annotate recognized the `.filter` call as an angular call.

**Comment by olov** [comment]
Hi! This is an old but that should not happen in recent versions of ng-annotate so please upgrade to the latest version (`npm install -g ng-annotate`) and see if the problem persists. If it does, please leave a comment with your ng-annotate version, a reduced test case and ng-annotate's output (all in JS). Thanks!

**Comment by philippfrank** [comment]
Thx @olov. I used a super old version of `gulp-ng-annotate`. Works now, closing.

**Comment by olov** [comment]
Super, thanks!
