### ISSUE TITLE
Over-greedy annotation for ES6 class

### ISSUE THREAD

**Issue by vivainio** [olov/ng-annotate#156]
I'm using Browserify, browserify-ngannotate and es6ify (Traceur).

I have a class like this, that gets exposed as Angular service:

```javascript
class Foo {
	constructor($filter) {
	// ...
	}
}

angular.module('mymod').service("Foo", Foo);

```

This mistakenly transpiles to:

```javascript
var Foo = ["$filter", function Foo($filter) {
	// ...
}];
```
(that is, Foo is no longer a constructor function but Array!)

If I do explicit DI, like:
```javascript
angular.module('mymod').service("Foo", ['$filter', Foo]);
```
It transpiles correctly to:

```javascript
var Foo = function Foo($filter) {
	// ...
};
```

Safer behavior would be to not annotate class declarations at all, or annotate them with Foo.$inject (something I planned to do anyway).

**Comment by olov** [comment]
Thanks for filing the issue! You seem to be using an old version of ng-annotate. Recent versions transform

```javascript
var Foo = function Foo($filter) {
};
angular.module('mymod').service("Foo", Foo);
```

into

```javascript
var Foo = function Foo($filter) {
};
Foo.$inject = ["$filter"];
angular.module('mymod').service("Foo", Foo);
```

Generally speaking, you still need to use `"ngInject"` (or `/*@ngInject*/`) to get your ES6 classes annotated properly, but semantic code breakages such as your original issue should not happen (with or without them).

**Comment by olov** [comment]
Closing. If you were able to repro your issue with a recent ng-annotate version then please re-open.
