### ISSUE TITLE
Removing unused dependencies

### ISSUE THREAD

**Issue by shprink** [olov/ng-annotate#158]
Hi,

Would it be possible for ng-annotate to remove unused dependencies from Angular' modules? A new option?

I'll be happy to help if you feel that it is a feature worth adding to your project.

Cheers

**Comment by olov** [comment]
As for now I don't think so, but thanks for offering to help. Unused dependencies is nothing more than unused function parameters and your linter should be able to warn for that (the actual removal you'd need to do manually).

Also https://github.com/olov/ng-annotate/issues/42

**Comment by shprink** [comment]
I do not think Angular's DI can be compare to function parameters in term of overhead but you are right simple linter would do.

cheers
