### ISSUE TITLE
Support for leading and trailing underscores

### ISSUE THREAD

**Issue by allenhwkim** [olov/ng-annotate#160]
First, I appreciate for your wonderful work.

As you see  in the following example, having an underscore as prefix and suffix for DI is very handful when you organize your Javascript, and it is perfectly legal in AngularJS.

I leared it from here, https://docs.angularjs.org/tutorial/step_05

>  // The injector ignores leading and trailing underscores here (i.e. _$httpBackend_).
>  // This allows us to inject a service but then attach it to a variable
>  // with the same name as the service in order to avoid a name conflict.

However, it ng-annotate does not seem work with this syntax, `_$scope_`, `_MyService_`, etc.

http://plnkr.co/edit/2vZGxggEcJJ7k4tSBpWa?p=preview

```
<!DOCTYPE html>
<html ng-app="plunker">
  <head>
    <script src="https://code.angularjs.org/1.4.0-rc.1/angular.js" data-semver="1.4.0-rc.1"></script>
    <script>
    var app = angular.module('plunker', []);
    
    //@ngInject
    app.controller('MainCtrl', function(_$scope_) {
      $scope = _$scope_;
      $scope.name = 'World';
    });
    </script>
  </head>

  <body ng-controller="MainCtrl">
    <p>Hello {{name}}!</p>
  </body>

</html>
```

**Comment by omsmith** [comment]
Hi Allen,

While, due to code re-use, this does work in actual applications - it isn't documented, nor should it be needed, outside of unit test use (the example you provided is for tests.

See #71 and #120.

**Comment by allenhwkim** [comment]
I want to provide some use case.

The following directive requires some custom function to use $http.
However it's hard to organize this code because `$http` is only available in directive function only;

```
(function(){
  'use strict';
  
  var myDirective = function($http) {
    return {
      restrice: 'A',
      require: '?ngModel'
      link: function(scope, element, attrs) {
        var someArray = attrs.foo;
        // need to make a function to isolate some code with $http
        var someVeryLongCustomFunction = function(array) {
          for (var i=0; i<array.length; i++) {
            $http(array[i]).success(function() {
              // ...
            })
            // ...
            // long
            // ...
            // ...
            // ...
          }
        };
        someVeryLongCustomFunction(someArray);
     }
  });
    
  angular.module('myApp').directive('myDirective', myDirective)
})();
```

By simply making $http available, the code can get better organized.
I personally think the following coding style is a log better the upper one.

```
(function(){
  'use strict';
  var $http;

  var someVeryLongCustomFunction = function(array) {
    for (var i=0; i<array.length; i++) {
      $http(array[i]).success(function() {
        // ...
      })
      // ...
      // long
      // ...
      // ...
      // ...
    }
  };

  var linkFunc = function(scope, element, attrs) {
    var someArray = attrs.foo;
    someVeryLongCustomFunction(someArray);
  };

  var myDirective = function(_$http_) {
    $http = _$http_;
    return {
      restrice: 'A',
      require: '?ngModel'
      link: linkFunc 
    }
  };
    
  angular.module('myApp').directive('myDirective', myDirective)
})();
```

It's been quickly closed, and I respect your decision not to open the debate again.

However, I highly recommend to make underscored arguments injectable for best code practices and better styling.

**Comment by omsmith** [comment]
While non-nested functions might be a best practice, assigning an injected variable outside of it's injected context most certainly is not.

I highly suspect what you actually want in this case is a [service](https://docs.angularjs.org/guide/services).

**Comment by allenhwkim** [comment]
A service are collection of sharable code. We do not put make it as a service just to organize code. All injected services are singleton, and there is no harm to access outside of of it outside of injected context.
