### ISSUE TITLE
Missing annotations for transpiled classes when using traceur@0.0.88+

### ISSUE THREAD

**Issue by gempesaw** [olov/ng-annotate#162]
Hi, thanks for your work on this package, I find it invaluable :D I'm using traceur to transpile es6 classes into es5, and then I run ng-annotate on the transpiled es5 code.

Apparently, traceur@0.0.88+ slightly changes how they transpile classes & constructors ? Or, perhaps I'm not passing traceur the right flags. Well, this is what I'm seeing for the following input:

```js
class MyController {
    constructor ( args ) {
        // body
    }
}
```

traceur@0.0.88 & 89 transpiles this to

```js
var MyController = (function() {
    function MyController(args) {}
    return ($traceurRuntime.createClass)(MyController, {}, {});
}());
```

And ng-annotate seems to be missing that type of declaration.

(Previously, with traceur@0.0.87, it does the fn expression & declaration on the same line, as solved in #84 and #95)

```js
// traceur output for v0.0.87, which ng-annotate is happy to fix up for us
var MyController = function MyController(args) {};
```

Right now, I've just pinned traceur@0.0.87, which still transpiles it the old way that you already accounted for in #95. 

[maybe useful gist of both transpilation outputs](https://gist.github.com/gempesaw/3e0e812c02348fad2187)

**Comment by olov** [comment]
ng-annotate is not going to be able to infer that traceurRuntime.createClass returns its first argument.

`"ngInject"` to the rescue!

```js
var MyController = (function() {
    function MyController(args) { "ngInject" }
    return ($traceurRuntime.createClass)(MyController, {}, {});
}());
```

=>

```js
var MyController = (function() {
    function MyController(args) { "ngInject" }
    MyController.$inject = ["args"];
    return ($traceurRuntime.createClass)(MyController, {}, {});
}());
```

**Comment by gempesaw** [comment]
fair enough, thanks!
