### ISSUE TITLE
Stop running in node v0.12 with --harmony flag

### ISSUE THREAD

**Issue by qiu8310** [olov/ng-annotate#174]
I run my program using `node --harmony ~/Workspace/node/test/bin/cli`

it stop running when anAnnotate, so I add some log on your source code, like this:

![qq20150607-1 2x](https://cloud.githubusercontent.com/assets/1094697/8022749/93e72164-0d1a-11e5-9434-bdbcabe11c89.png)
 
Run it again, it end like this:

![qq20150607-1](https://cloud.githubusercontent.com/assets/1094697/8022751/b12c5c62-0d1a-11e5-980d-394f04e43b71.png)

So I change that `let` key word ( first picture, wraped in red ) to `var`, it works again.

Weird!

**Comment by olov** [comment]
how does your `cli` program invoke ng-annotate?

**Comment by qiu8310** [comment]
Like #173 

This may not your source code problem, maybe my node.js or my system problem.
