### ISSUE TITLE
Constructor class injection

### ISSUE THREAD

**Issue by mfilotto** [olov/ng-annotate#175]
Hi,
Would be very nice to have injection inside the constructor method of ES6 class.
Thanks for this great tool by the way :+1:

**Comment by olov** [comment]
Add `"ngInject";` immediately inside your constructor and transpile using latest Babel. If that doesn't work for you then please provide sample input, expected output, real output and ng-annotate version. Thanks!

**Comment by mfilotto** [comment]
yes I use this already but I meant without that directive.

**Comment by mfilotto** [comment]
Wahoo I removed all my 'ngInject'; inside the controller constructors and the injections are stil there.
You already improve this then 
Good job guys !

**Comment by olov** [comment]
We did? :-)  Which transpiler do you use and would you be able to provide a small input/output example, just for my curiosity?

**Comment by mfilotto** [comment]
I use typescript trhough webpack loader
