### ISSUE TITLE
Support for angular-route-segment

### ISSUE THREAD

**Issue by leoetlino** [olov/ng-annotate#179]
Would it be possible to add support for [angular-route-segment](https://github.com/artch/angular-route-segment)? It is basically a module that builds on `ngRoute` to provide features similar to `ui-router`, so the code looks similar to `ngRoute` (but with more features):

```
var watchForService = function ($rootScope) {
    return $rootScope.service.id;
};

$routeSegmentProvider
    .when('/', 'dashboard')
    .when('/manage', 'manage')
    .when('/manage/information', 'manage.information')
    .segment('dashboard', {
        resolve: {
            summary: function ($http) {}
        }
    })
    .segment('manage', {
        resolve: {
            service: function ($http) {}
        },
        controller: function ($scope, $http) {}
        watcher: watchForService
    })
    .within()
    .segment('information', {
        watcher: watchForService
    });
```

* `$routeSegmentProvider.segment({ resolve: function () {} }`
* `$routeSegmentProvider.within().segment({ resolve: function () {} }` for child route segments
* `$routeSegmentProvider.segment({ controller: function () {} }`
* `$routeSegmentProvider.within().segment({ controller: function () {} }` for child route segments
* `$routeSegmentProvider.segment({ watcher: function () {} }`
* `$routeSegmentProvider.within().segment({ watcher: function () {} }` for child route segments

I initially wanted to make a pull request, but wasn't sure if this should be implemented as a plugin or right in `ng-annotate-main.js`.

Thanks!

**Comment by olov** [comment]
I'll be happy to merge a PR with this as an optional (plugin).

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
