### ISSUE TITLE
ng-annotate does not recognize `Module.decorator`...?

### ISSUE THREAD

**Issue by al-the-x** [olov/ng-annotate#181]
I can see from previous issues (#82 and #108) that `decorator` functions that don't belong to Angular are _not_ decorated... Is the current behavior to annotate _only_ `$provider.decorator` and _not_ `Module.decorator`...?

**Comment by gkalpak** [comment]
:+1:

**Comment by al-the-x** [comment]
So is that a yes? I noted in a recent project that injectables chained _after_ `.decorator` were also not decorated, e.g.

    angular.module('module')
      .config(function($someProvider){
        // gets annotated
      })
      .decorator(function(someService){
        // not annotated
      })
      .controller('SomeController', function(){
        // also not annotated
      })
      // nothing else annotated

I worked around the problem by sticking the decorator at the end of the chain and using `/* @ngInject */` comments in front of it.

**Comment by gkalpak** [comment]
It was not exactly a _yes_, rather a _I've observed the same behaviour and would love to have this fixed, so that `ngAnnotate` will properly recognie `angular.decorator()` as well_.
(But I tried to be laconic :smile:)

**Comment by olov** [comment]
The current behavior is that ng-annotate only supports `$provider.decorator`. See the linked issues for further explanation of why.

**Comment by gkalpak** [comment]
@olov, I am not at all familiar with the inner workings of `ngAnnotate`, but wouldn't it be possible to differentiate `Module`'s `decorator` from other `decorators` ?

**Comment by al-the-x** [comment]
Without doing some fairly complicated static analysis of the input, I'm not
so sure. The previous issues I referenced point to some difficulty
resolving the receiver of the `decorator` method as an actual module
instance, so I assume there's no such analysis being done at the moment.
All in all, probably not worth the effort.

**Comment by readme42** [comment]
:+1: 
It would be great, if angular module's decorator would work!
