### ISSUE TITLE
After migrate from ngmin to ng-annotate Less plugin crash after ng-annotate task runs

### ISSUE THREAD

**Issue by mmadrigalac** [olov/ng-annotate#182]
Hi,

Currently I'm migrating a project that is using ngmin to ng-annotate.
After check the documentation I saw there should not be problem by renaming my old ngmin task to ng-annotate after proper installation was done.
However I noted Less plugin ( grunt-contrib-less ) is failing whenever ng-annotate runs in the same grunt task, it's returning this error:

Fatal error: builder is not defined
ReferenceError: builder is not defined

I've done several tests where not using ng-annotate will result in no problem for Less task to run.

Could you please help me on this?
Thanks in Advance!

**Comment by olov** [comment]
Please open up the issue for the plugin instead. If you can submit a reduced test case with input and output from command-line ng-annotate, then I'll look into it.
