### ISSUE TITLE
More extensive reference-following

### ISSUE THREAD

**Issue by jerguslejko** [olov/ng-annotate#183]
According to the docs, any other definitions than stated will be ignored. Would it be possible to support this one?

    var TestController;

    TestController = function( $scope )
    {
    };

    angular
	    .module('app')
	    .controller( 'TestController', TestController );

This is standard output when using CoffeeScript, and the fact that the definition is not on a same line as declaration makes ng-annotate ignore that controller.

thanks

**Comment by olov** [comment]
I would accept a PR for that with the condition that TestController must only be assigned once.

**Comment by jergush** [comment]
Thats perfectly fine with me, I'm looking forward to use ng-annotate within my project

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
