### ISSUE TITLE
cannot annotate properly when the controller is inside an object

### ISSUE THREAD

**Issue by ericcky** [olov/ng-annotate#187]
```
var myApp = angular.module('myApp', []);
var obj = {};
obj.ctrl = function ($scope) {};
myApp.controller('myCtrl', obj.ctrl);
```
https://github.com/olov/ng-annotate/issues/183

I found that if controller is in a object, ng-annotate will ignore it. Is it possible to support that structure?
thanks.

**Comment by olov** [comment]
Will that code even work in Angular? If so, can you please link to documentation for the `.ctrl` property?

**Comment by ericcky** [comment]
yes, it works in angular.
http://plnkr.co/edit/D1YwtPZXxOekK7xsnWsV?p=preview

**Comment by olov** [comment]
Forgive me I didn't look at your code closely enough and thought that you were sending in `obj` instead of `obj.ctrl` as a parameter. Ok, now I get your question. No, that won't be supported but feel free to do `obj.ctrl = function ($scope) { "ngInject"; ... };` and things will work fine.

**Comment by ericcky** [comment]
Thanks for your reply, this is work for me, but adding `"ngInject";` one by one is really annoying.

**Comment by olov** [comment]
hopefully not as annoying as manually creating an inject-array and keeping it consistent with the parameters.

**Comment by DSchau** [comment]
Just a note that this may become more of an issue as people begin to use something like Webpack to bundle assets together.

Consider the following code:

```javascript
'use strict';
function LoadingInterceptorConfig($httpProvider) {
  $httpProvider.interceptors.push('LoadingInterceptor');
}

export default LoadingInterceptorConfig;
```

then the import, itself:

```javascript
'use strict';
import LoadingInterceptorConfig from './sample-loading-interceptor.config';

export default angular.module('sample.loadingInterceptor', [])
.config(LoadingInterceptorConfig);
```

which creates (before ng-annotate runs) the following structure, which is essentially doing something similar to the problem described, e.g. accessing an object property to get the function reference.

```javascript
Object.defineProperty(exports, '__esModule', {
  value: true
});

var _sampleLoadingInterceptorConfig = __webpack_require__(2);

var _sampleLoadingInterceptorConfig2 = _interopRequireDefault(_sampleLoadingInterceptorConfig);

'use strict';
exports['default'] = angular.module('sample.loadingInterceptor', [])
.config(_sampleLoadingInterceptorConfig2['default'])

module.exports = exports['default'];
```

However, as @olov noted, adding the following *does* work, it'd just be ideal if somehow ng-annotate was able to work with a module bundler/object functions.

```javascript
'use strict';
function LoadingInterceptorConfig($httpProvider) {
  'ngInject';
  $httpProvider.interceptors.push('LoadingInterceptor');
}

export default LoadingInterceptorConfig;
```

**Comment by olov** [comment]
@DSchau it's just hard to do that with static analysis and I don't believe it will happen. `"ngInject";` is not that bad! :)
