### ISSUE TITLE
Named Function Annotation (Babel/Webpack/ngAnnotateLoader)

### ISSUE THREAD

**Issue by patrickhousley** [olov/ng-annotate#189]
Please see the below issue. I am currently using webpack, ng-annotate, ng-annotate-loader, and babel. I am getting an error stating my code is not using explicit annotations.

https://github.com/huston007/ng-annotate-loader/issues/9

**Comment by patrickhousley** [comment]
I believe I was able to find the answer: https://github.com/olov/ng-annotate/issues/64#issuecomment-78462297. Below is the regexp I came up. Any comments on it?

```javascript
(?:[_]?angular[\d]*\.)?[_]?module[\d]*(?:\[['"]?[\w\d]+['"]?\])\.(?:(?:factory)|(?:service)|(?:controller)|(?:directive)|(?:run)|(?:config)){1}
```

**Comment by patrickhousley** [comment]
I shortened the regexp down after reading the previously mentioned issue comment. I am no longer having issues with the routingConfig area but it is not matching the code of the originally linked issue (included below to make this easier).

```javascript
(?:[_]?angular[\d]*(\[[\'\"]?[\w\d]+[\'\"]?\])?\.)?[_]?module[\d]*(?:\[[\'\"]?[\w\d]+[\'\"]?\])?.*
```

Problem code:
```javascript
import '../common/responsive.service'
import '../common/cookie.service'

module.service('menuConfigService', MenuConfigService);

function MenuConfigService(responsiveUtils, cookieService) {
  ...
}
```

**Comment by olov** [comment]
If I understand your problem correctly then you're concerned that ng-annotate does not understand that `_module3['default'].service(..)` is a service declaration, and that it for that reason can't follow the MenuConfigService reference and annotate it properly.

First things first. `function MenuConfigService(responsiveUtils, cookieService) { "ngInject"; ... }` should work fine, but I understand that you want things to work as automatic as possible.

So now your need to tweak the `regexp` option to match `_module3['default']` properly. This is the default (from README): "Not using the option is the same as passing `--regexp "^[a-zA-Z0-9_\$\.\s]+$"`, which means that the callee can be a (non-unicode) identifier (foo), possibly with dot notation (foo.bar).". The regexp `/^[a-zA-Z0-9_\$\.\s]+$/` does not match the string `"_module3['default']"` so just create your own regexp that does. Make it as strict or relaxed as you want to, but be aware that your risk of false positives increases the more relaxed it is.

**Comment by patrickhousley** [comment]
Thanks @olov, I came to the same conclusion. The problem now is that my regexp matches "_module3['default']" but it is not working. It also seems that the default identifier is relatively relaxed. Are there truly any downsides to false positives?

**Comment by olov** [comment]
See the example below. I just added support for `'`, `[` and `]` to the regexp. The problem with false positives is that if ng-annotate is fooled into thinking that your non-angular code is angular code and starts rewriting it, well then things may break. Feel free to use the regexp as a start and then you can make it more strict if you need to. Closing the issue.

```js
~/projects/ng-annotate/tests-issues % cat issue189.js
_module3['default'].service('menuConfigService', MenuConfigService);
function MenuConfigService(responsiveUtils, cookieService) {
}

~/projects/ng-annotate/tests-issues % ng-annotate --regexp "^[a-zA-Z0-9_\$\.\s\[\]\']+$" -a issue189.js
_module3['default'].service('menuConfigService', MenuConfigService);
function MenuConfigService(responsiveUtils, cookieService) {
}
MenuConfigService.$inject = ["responsiveUtils", "cookieService"];
```

**Comment by patrickhousley** [comment]
@olov Thanks for the assistance. The regexp does work but it causes other code to not get annotated properly. Below is sample code that gets properly annotated without passing the regexp but gets missed with the regexp. Is there any way the regexp option could be additive in nature? As in act in addition to any current matching regexp or code you have?

```javascript
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _locale = __webpack_require__(1704);

var _locale2 = _interopRequireDefault(_locale);

exports['default'] = function (module) {
  module.config(function routingConfig($locationProvider, $urlRouterProvider, $stateProvider, $provide) {
    ....
  });
}
```

**Comment by patrickhousley** [comment]
Scratch my last @olov, the below regexp seems to be catching both cases. Please let me know if you see any potential pitfalls with this regexp. It may also be nice to still consider the passed regexp as additive and possibly allow for multiples.

```javascript
(?:[_]?angular[\d]*(\[[\'\"]?[\w\d]+[\'\"]?\])?\.)?[_]?module[\d]*(?:\[[\'\"]?[\w\d]+[\'\"]?\])?.*
```

**Comment by olov** [comment]
@patrickhousley the regexp I provided as an example works for your last snippet as well. As for making a user-provided regexp "additive", that's not going to work because the idea is that the user will often want to provide a more strict regexp than the default one. It is however possible to just copy the default regexp and `|` it with your own one.

**Comment by patrickhousley** [comment]
@olov Thanks, your help is much appreciated.
