### ISSUE TITLE
Do not annotate ui-router's $urlRouterProvider.otherwise

### ISSUE THREAD

**Issue by gabrielmaldi** [olov/ng-annotate#19]
Currently, this:

``` javascript
$urlRouterProvider.otherwise(function ($injector) {
  //...
});
```

is being annotated into:

``` javascript
$urlRouterProvider.otherwise(["$injector", function ($injector) {
  //...
}]);
```

But `ui-router` expects a function:

``` javascript
this.otherwise =
    function (rule) {
      if (isString(rule)) {
        var redirect = rule;
        rule = function () { return redirect; };
      }
      else if (!isFunction(rule)) throw new Error("'rule' must be a function");
      otherwise = rule;
      return this;
    };
```

and already passes `$injector` as a parameter to `otherwise`:

``` javascript
function update() {
        function check(rule) {
          var handled = rule($injector, $location);
          if (handled) {
            if (isString(handled)) $location.replace().url(handled);
            return true;
          }
          return false;
        }
        var n=rules.length, i;
        for (i=0; i<n; i++) {
          if (check(rules[i])) return;
        }
        // always check otherwise last to allow dynamic updates to the set of rules
        if (otherwise) check(otherwise);
      }
```

I'm not being able to keep `ng-annotate` from annotating this by using:

``` javascript
regexp: /^((?!otherwise).)*$/
```

I probably misunderstood the `regexp` option, though.

Workaround:

``` javascript
var urlRouterProvider = $urlRouterProvider;
urlRouterProvider.otherwise(function ($injector) {
  //...
});
```

**Comment by stodolos** [comment]
@gabrielmaldi Did you ever find a way to handle $urlRouterProvider.otherwise properly?  If I turn mangle on in my uglify settings, I get the error, and since it won't take the annotation syntax, what can be done if I want everything else mangled?

Thanks in advance

**Comment by gabrielmaldi** [comment]
@stodolos what version of `ng-annotate` are you using? I'm using `0.10.0` and `$urlRouterProvider.otherwise(function () {});` is annotated fine. This should just work as per 2587e8781ee1fd6bd5932f29c1bc5c53ff0f28ae (see the tests), but maybe it broke on a later version. Can you check if it works for you with `0.10.0` and confirm if it is broken with the most recent version? Thanks!

**Comment by stodolos** [comment]
Well I'm not using ng-annotate (and maybe that's the problem).  I'm using _uglify _to _mangle_ my source, and it all worked fine until I started `$urlRouterProvider.otherwise`.  My first reaction was to pass an array, which of course fails as you noted.  Hopefully I'm just missing something simple/should be using ng-annotate some how.

**Comment by gabrielmaldi** [comment]
@stodolos you're right 😄 That's what ng-annotate is for, it converts regular functions into Angular's annotated syntax (which uses string arrays in order to know which parameters to inject) so that you can safely uglify your code (otherwise parameter names would be minified to letters and Angular wouldn't know how to inject them). Take a look at ng-annotate, using it will solve your issue. Cheers!

**Comment by stodolos** [comment]
Can you share what your annotated call to otherwise looks like with `$injector` as a parameter?

**Comment by stodolos** [comment]
Never mind... I had two "config" functions (one for my module config and another from a directive's config, which came from a template I purchased), and I was blaming the module config the whole time.  I finally came to realization when I enabled `ng-strict-di`.  That clearly told me the name of the piece causing the issue, and then I was able to narrow it down.
