### ISSUE TITLE
Alternative declaration support

### ISSUE THREAD

**Issue by dctdevelop** [olov/ng-annotate#190]
Hey Guys, 

I was noticing that there are hackish ways of implementing ng-annotate in compile-to-js languages, such as coffescript (i.e decalring a null statement)

While I believe that this is coffee-script's fault for not adding the comment on the declaration, I thought of a possible solution.

Is it possible to simply declare the $inject (as null, undefined, etc) property on the object we want annotated? 

```coffeescript
module.exports = ($scope)->
  $scope.foo = "foo"
  return

module.exports.$inject = null # [], undefined, etc. (falsey value for ng-annotate to populate)
```

ng-anotate would populate the field on this line. Based on the object in question.

Regards.

**Comment by dctdevelop** [comment]
Should have looked more deeply into existing issues.
Apologies  #81

**Comment by olov** [comment]
Did you try `"ngInject";` at the beginning of the function you wanted annotated?

**Comment by dctdevelop** [comment]
Yeah

I resolved to 

```coffescript
null
###@ngInject###
module.exports = ($scope, ...)->
  ...
```

Without the `null` statement at the top, coffescript will place its required functions between the annotation or directive prologue (such when using `_item in _array`) syntax.

http://bit.ly/1MXR1YT


Regards

**Comment by olov** [comment]
Feel free to try the following instead:
```
module.exports = ($scope, ...) ->
    "ngInject";
    ....
```

**Comment by dctdevelop** [comment]
I totally missed that in the docs, and also misunderstood it your comments. Apologies.

Thanks for the support.
