### ISSUE TITLE
Documentation of problem annotating function expressions declared at top of coffeescript files

### ISSUE THREAD

**Issue by AJeezy9** [olov/ng-annotate#194]
Been racking my brain for the last hour or so trying to find out what was going wrong with minifying an Angular app until I finally discovered that the coffeescript compiler was pushing the `/* @ngInject */` comment above the variable declarations when that comment preceded a function expression at the top of a file, thus preventing ngAnnotate from associating the function with the requested injection. For purposes of clarity, this problem occurs because, when at the top of a file, coffeescript compiles this

```coffee
### @ngInject ###
myController = (dependencies...) ->
```
to this
```js
/* @ngInject */
var myController;
myController = function(dependencies...) {
	...
}
```

Unable to find a workaround, I stumbled onto to the discussion of this problem #152, and I agree that the fault can ultimately be placed at the coffee compiler's feet.

However, being that this is a known issue, can this problem (& those similar to it in other languages) be documented or otherwise noted in a known issues section? 

It can be hard to discover the reason to why your seemingly annotated & minified app is not working, especially when all you have to go on is otherwise indecipherable AngularJS's error messages.

Also, if anyone does have a workaround, I'd love to hear it. Manual injection is so 2012...

**Comment by olov** [comment]
A problem with #152 was that no-one opened up a CoffeeScript issue. For reference, the TypeScript `tsc` compiler had a similar problem, I opened up an issue and they fixed it within a month or two. After a CS issue is opened I'll evaluate the need for workarounds in #152.

Regarding our documentation, I completely agree. It would be great if the ng-annotate README had (at least) Babel, TypeScript and CoffeeScript sections. Will accept PR's!

**Comment by olov** [comment]
And regarding troubleshooting why your minified code doesn't work in Angular, suspecting a missing DI array, the trick is to use `ng-strict-di` and run ng-annotate on your original (unminified) source.
