### ISSUE TITLE
$controllerProvider.register() is not annotated

### ISSUE THREAD

**Issue by timostamm** [olov/ng-annotate#195]
First, thank you for the great work, Olov. 

I noticed that ng-annotate does not understand ``$controllerProvider.register()``. Example:

    angular.module('test', [])
    .config(function( $controllerProvider ){
      // NOT annotated:
      $controllerProvider.register('FooCtrl', function( $scope ){
        $scope.foo = "FOO";
      }); 
    });

I guess it just flew under the radar?

**Comment by olov** [comment]
Thanks. This should be added to the next release.

**Comment by olov** [comment]
released in 1.1.0
