### ISSUE TITLE
$modal has been renamed to $uibModal in ui-bootstrap 0.14.0

### ISSUE THREAD

**Issue by mattlewis92** [olov/ng-annotate#200]
See: https://github.com/angular-ui/bootstrap/commit/8c7b9e4

Thanks! :smile:

**Comment by olov** [comment]
Thanks for the heads-up! I guess we'll need to support both `$modal` and `$uibModal` then. Will do for next release.

**Comment by mattlewis92** [comment]
Fantastic, thank you!

**Comment by char0n** [comment]
Any workaround now ?

This is what i can think of:

1.) explicitly annotate all javascript code with @ngInject
2.) some sort of override on config level

Any suggestions ?

**Comment by olov** [comment]
The workaround is to annotate your angular-ui modals with `"ngInject"` or `/*@ngInject*/`.

**Comment by theatrain** [comment]
Any update on when this will be updated?

**Comment by kld87** [comment]
+1

I notice there's a pull open to fix this issue

**Comment by olov** [comment]
released in 1.1.0

**Comment by eavestn** [comment]
@olov  Should I now be seeing `$modal` instead of `$uibModal'?

**Comment by olov** [comment]
@eavestn ng-annotate understands $uibModal.open and $modal.open, whichever you use

**Comment by jjayaraman** [comment]
Thanks it helped... I was struggling with old name $modal in a old code..
