### ISSUE TITLE
Sourcemaps missing mappings for closing brace

### ISSUE THREAD

**Issue by tyson-benson** [olov/ng-annotate#201]
Hi there,

Great work on the plugin so far, I found an issue using the sourcemaps, there is no mapping produced for the closing brace for control blocks and functions. For example, when debugging in Chrome i can put a breakpoint on the third line in the source mapped TypeScript before applying ng-annotate example below:

```
var foo = () => {
    doSomething();
} // <-- can put breakpoint here
```
```
if (condition) {
    foo();
} // <-- can put breakpoint here
```

But after using ng-annotate, the lines on which i can put breakpoints are limited to the top two in the examples above. Is there a possibility you can change the sourcemap generator to create the appropriate mappings to preserve support for this?

Let me know if you need more info, it is easy to reproduce. In chrome it is easier to spot, as the lines with a closing brace are grayed out and you cannot insert the breakpoints.

**Comment by olov** [comment]
Thanks for the bug report - this is hopefully easy to fix. @smrq would you be able to take a look at it?

**Comment by olov** [comment]
I'd merge a PR fixing this issue.

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
