### ISSUE TITLE
Sourcemaps cannot be read from external .map files

### ISSUE THREAD

**Issue by tyson-benson** [olov/ng-annotate#202]
I noticed that ng-annotate is hard-coded to read inlined source mappings, would it be possible to add a configuration for reading sourcemaps from an external source/file (e.g. a .map file)?

**Comment by olov** [comment]
+@smrq

**Comment by CxRes** [comment]
Or pass in a sourcemap object for that matter...

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
