### ISSUE TITLE
Migration from @ngInject to "ngInject"

### ISSUE THREAD

**Issue by bholloway** [olov/ng-annotate#206]
@olov as discussed in bholloway/nginject-loader#1.

I've attempted a toolset to migrate from the legacy(?) `@ngInject` syntax to the newer `"ngInject"` directive syntax.

I have a couple of things that are functional but not yet published.
* [bholloway/nginject-migrate](https://github.com/bholloway/nginject-migrate) A migration tool; primarily API but with basic CLI too.

* [bholloway/nginject-loader#2.0.0-rc](https://github.com/bholloway/nginject-loader/tree/2.0.0-rc) The Webpack nginject-loader reimagined as a migration solution.

Definitely appreciate any feedback you have.

I've held off on publishing the migration tool in case you have any view on the naming, the API, or any other aspect best solved early.

Best case I'll be living with the Webpack loader for a while (days,weeks,tbd) before I publish and deprecate nginject-loader version 1.x.x.

**Comment by olov** [comment]
Sorry for the late feedback. Seems great, go for it!
