### ISSUE TITLE
Unknown provider error with $mdDialog

### ISSUE THREAD

**Issue by orangesoup** [olov/ng-annotate#208]
Hey!

I'm using Angular Material (latest) and I've come across this error which I can't figure out for hours now. It seems that if I use a custom controller the minified file just doesn't work. Could this be a bug or am I missing something obvious?

````javascript
$scope.showConfirm = function(ev) {
	var confirm = {
		templateUrl: 'pat.html',
		targetEvent: ev,
		scope: $scope,
		preserveScope: true,
		controller: function DialogCtrl($scope, $mdDialog) {
			$scope.cancel = function () {
				$mdDialog.hide();
			}
			$scope.submit = function () {
				$mdDialog.hide(true);
			}
		}
	};
	$mdDialog.show(confirm).then(function() {
		whatever();
	});
};
````

**Comment by olov** [comment]
ng-annotate is limited in the patterns it recognizes. It would detect `$mdDialog.show({...})`. So it's a known limitation. The recommendation is to use an explicit annotation like so: `controller: function DialogCtrl($scope, $mdDialog) { "ngInject"; ...})`.
