### ISSUE TITLE
Does not know angular('foo').component()

### ISSUE THREAD

**Issue by landru29** [olov/ng-annotate#216]
I'm using this polyfill https://github.com/toddmotto/angular-component

It would be great that ng-annotate could work with
````
angular('foo').component('hello', {
    controller: function($scope) {
    }
});
````

For more info, see https://toddmotto.com/exploring-the-angular-1-5-component-method/

**Comment by olov** [comment]
That's supported since ng-annotate 1.1.1 (but use `angular.module('foo').component` or `myMod.component`).

```js
~/projects/ng-annotate % cat tests-issues/issue216.js
angular.module('foo').component('hello', {
    controller: function($scope) {
    }
});
~/projects/ng-annotate % ./ng-annotate-harmony -a tests-issues/issue216.js
angular.module('foo').component('hello', {
    controller: ["$scope", function($scope) {
    }]
});
```
