### ISSUE TITLE
annotate .ts files

### ISSUE THREAD

**Issue by zanettin** [olov/ng-annotate#217]
Hi @olov 

Thanks  a lot for your great work on ng-annotate!
I've switched from ES5 to ES6 syntax using typescript. Since my IDE is compiling the .ts files to .js, I don't know, when the transpiling is done and my gulp task can start with the annotation.
So my question is, if it is possible to annotate already in the ts file instead of writing the injection manually
`````
static $inject = ["$q", "MyService"];
````
thanks for your reply

**Comment by olov** [comment]
I don't intend to support TypeScript as input to ng-annotate. Did you try doing this: https://github.com/olov/ng-annotate#es6-and-typescript-support ?
