### ISSUE TITLE
How to handle transpiled code's source map when passed to ngAnnotate?

### ISSUE THREAD

**Issue by Rush** [olov/ng-annotate#218]
So I've ran babel on my code and I get a string with the transpiled code and the inline source map at the end, like so:

```
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJz.....
```

Then I run ngAnnotate
```
let res = ngAnnotate({add: true, map: {inline: true, inFile: "source.js"}}, transpiledCodeWithInlineSourceMap);
```

I expect to see a source map mapping all the way to the original file but it's not the case? Any tips how to handle it?

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
