### ISSUE TITLE
ng-annotate not working if exporting a module

### ISSUE THREAD

**Issue by davidreher** [olov/ng-annotate#224]
I have some code which looks like this:
```javascript
export class PlainTextCtrl {
  /* @ngInject */
  constructor($scope) {
    this.containerCtrl = $scope.containerCtrl;
  }
}
```
after running it through babel, I am getting the following:
```javascript
var PlainTextCtrl =
  /* @ngInject */
  exports.PlainTextCtrl = function PlainTextCtrl($scope) {
    _classCallCheck(this, PlainTextCtrl);
    this.containerCtrl = $scope.containerCtrl;
  };
}
```

When I run this through ng-annotate nothing happens. But it should add the following:

```javascript
PlainTextCtrl.$inject = ['$scope'];
```
or
```javascript
exports.PlainTextCtrl.$inject = ['$scope'];
```

how to get around this issue?

I am using ng-annotate 1.2.0

**Comment by davidreher** [comment]
What works is using `'ngInject'` in the constructor, but it would be great to have the other one working as well ;)

**Comment by olov** [comment]
Using `/*ngInject*/` with transpilers is brittle because they tend to rearrange things. `"ngInject"` is the way to go!

**Comment by nicbou** [comment]
Here is an example, if you are parsing the thread and wondering if it's what you are looking for:

## Before

```
export default class ItineraryItemService {

  constructor/* @ngInject*/($rootScope, Config, ItineraryItem) {
    ...
  }
...
```

## After
```
export default class ItineraryItemService {

  constructor($rootScope, Config, ItineraryItem) {
    'ngInject';
    ...
  }
...
```

Thank you for the help, @olov !
