### ISSUE TITLE
the comment way to use ng-annotate .

### ISSUE THREAD

**Issue by lili21** [olov/ng-annotate#225]
the `readme` dose not cover well. Do all those comment way work ?
```
/** @ngInject */
/** @nginject */
/** inject */
/* @inject */
```
how many comments way can be used ?

and here is the weird situation I meet with。I am using [ng-annotate-loader](https://www.npmjs.org/package/ng-annotate-loader).

![2016-01-26 4 54 07](https://cloud.githubusercontent.com/assets/4456380/12576212/0a9a9680-c44d-11e5-96b8-160511fa653c.png)

It works well when using `/** @ngInject */`。

![2016-01-26 4 56 49](https://cloud.githubusercontent.com/assets/4456380/12576266/6ea25cda-c44d-11e5-974e-7858d604715b.png)

no `$inject` for `NsServer`, so it does not work when using `/** @inject */`. right ?

But how about this ?
![2016-01-26 5 03 12](https://cloud.githubusercontent.com/assets/4456380/12576385/4d59a78a-c44e-11e5-962b-a10bf91e1b04.png)

Looks like working fine. 

the only difference between those `/** @inject */` situations is the size of the code bases.

So what is the safest way to make it work ?

**Comment by olov** [comment]
From your example, `/* @inject */` does not affect ng-annotate at all. ng-annotate succeeds in annotating one of the cases anyways using static analysis.

As for how to write the comment, do it however you want. `/* @ngInject */`, `/*@ngInject*/`, `/** @ngInject */`, `// foo @ngInject bar` etc all work fine. But the recommended way is to use `"ngInject"`, as pointed out in the README.

**Comment by lili21** [comment]
@olov You meat ng-annotate understands
```
angular.module('app', [])
    .ctrl('ctrl', ctrl)
    .factory('NsServer', NsServer)
```
and does not understand 
```
_angular2.default.module('app').factory('NsServer', NsServer)
```

**Comment by olov** [comment]
That's correct. You can teach it to understand the latter form as well, see https://github.com/olov/ng-annotate/blob/master/IMPLICIT.md (search for regexp on page).

**Comment by lili21** [comment]
@olov  Now I got it. Thanks. Awesome job, by the way.
