### ISSUE TITLE
ng annotate fails when using a variable for factory name

### ISSUE THREAD

**Issue by scamden** [olov/ng-annotate#230]
```
var moduleName = 'nameeee'
angular.module(moduleName, [
  'aDep'
])

.factory(moduleName, function($q, ResourceSrvc) {
```

fails to annotate

**Comment by scamden** [comment]
@olov we use this almost everywhere any quick workarounds?

**Comment by olov** [comment]
just use `"ngInject"`, like so: `... .factory(moduleName, function($q, ResourceSrvc) { "ngInject"; ...`

**Comment by scamden** [comment]
@olov i said a quick workaround... i have literally hundreds of this case that i have to go add ngInject to...

this shouldn't be too hard a case to detect should it?

**Comment by olov** [comment]
We don't support matching these forms for a reason and if you're curious to learn more then check out the old issues (start with #20 and #22). My best advice to you is to use `"ngInject"`.

**Comment by scamden** [comment]
ah false positives got it, ok well no worries i did a world wide find and replace and we're looking pretty good. thanks for making a rad tool!

**Comment by olov** [comment]
np!
