### ISSUE TITLE
Support for annotating template and templateUrl properties on angular 1.5 component

### ISSUE THREAD

**Issue by martiansnoop** [olov/ng-annotate#231]
ng-annotate version: 1.2.1

It appears that with the new component, the template and templateUrl properties can also be a function called by the injector (forgive the toy example):

```javascript 
angular.module("myModule", [])
   .component("myComponent", {
        template: function($log) {
            $log.debug("doing a thing");
            return "<div>My Template</div>"
        },
       ...
 });
```

It doesn't look like ng-annotate is currently annotating these, though, so I had to fall back to the array syntax:
```javascript
        template: ["$log", function($log) {
            $log.debug("doing a thing");
            return "<div>My Template</div>"
        }],
```

**Comment by gaelduplessix** [comment]
+1

However you can avoid the array syntax using an explicit annotation:
```javascript
// @ngInject
templateUrl: ($locale) => 'views/' + $locale.id + '/app/app.html'
```

**Comment by michahell** [comment]
Correct, the new angular 1.5 way of defining components brakes ngAnnotate / uglify.
```Unknown provider: aProvider <- a```

**Comment by brunomrpx** [comment]
:+1:

**Comment by konclave** [comment]
+1

**Comment by rothlis** [comment]
+1

**Comment by jeremypele** [comment]
+1

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245

**Comment by Splaktar** [comment]
This is also an issue with controllers, i.e. this doesn't work:
```
angular.module('myApp').component('sox', {
  controller: SoxController,
...
});

function SoxController($rootScope) {
...
```

While this does:
```
angular.module('myApp').component('sox', {
  controller: SoxController,
...
});
SoxController.$inject = ['$rootScope'];
function SoxController($rootScope) {
...
```

**Comment by canac** [comment]
This feature would be useful in my application as well. Explicit annotation works fine, but it would be nice if this were automatic. @olov Does your closing this issue mean that this feature won't ever be added?

**Comment by omsmith** [comment]
@canac changes won't be made to ng-annotate going forward: https://github.com/olov/ng-annotate/issues/245
