### ISSUE TITLE
Support ES2015 natively

### ISSUE THREAD

**Issue by eddiemonge** [olov/ng-annotate#237]
It'd be nice to see support for ES2015 without having to first transpile it to ES5 code. As more browsers support ES2015, I think we will see a declining need for the transpiler step so it'd be good to see this support it as well.

**Comment by olov** [comment]
I won't be able to donate the time needed for supporting this and I'm not very fond of adding additional complexity to ng-annotate. If someone steps up to write and maintain the needed code, I'll be happy to merge a PR.

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245

**Comment by schmod** [comment]
This is very specifically being addressed in #245, so please head over there if you're interested.
