### ISSUE TITLE
Implicit annotations support for ngDialog module

### ISSUE THREAD

**Issue by slavafomin** [olov/ng-annotate#239]
Hello!

Thank you for this great library!

However, it would be great if you will be able to add implicit annotations support for [ngDialog](https://github.com/likeastore/ngDialog) module (it's quite popular). It uses [`resolve`](https://github.com/likeastore/ngDialog#resolve-objectstring-function) and [`controller`](https://github.com/likeastore/ngDialog#controller-string--array--object) properties to specify resolves and controllers for dialogue windows.

Thanks!

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
