### ISSUE TITLE
Using ng-annotate to detect namespace collisions?

### ISSUE THREAD

**Issue by parlarjb** [olov/ng-annotate#243]
I'd like to use `ng-annotate` to detect something like this:

```
angular.module('foo')
    .factory('XYZ', function () {})
    .service('XYZ', function () {});
```
i.e. detecting if someone has accidentally assigned the same name to two different factories/controllers/services/directives/etc.

The way I was thinking about doing this is to write a plugin that keeps a list of all names that it sees, and throwing an error whenever it comes across a duplicate.

But I'm not sure of all the properties available on a given `node` passed to the plugin `match`, so I'm not sure yet what to look for.

Any pointers would be appreciated!

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245

**Comment by schmod** [comment]
This might be a better task for [`eslint-plugin-angular`](https://github.com/Gillespie59/eslint-plugin-angular).

There's also [`ng-directive-parser`](https://github.com/jantimon/ng-directive-parser), which could be adapted to this purpose, although it's worth noting that it's perfectly legal for multiple directives to have the same name.

Finally, I'd also suggest opening a bug in the Angular bug-tracker if this is a persistent problem for you.  There are quite a few aspects of Angular's DI that seem to encourage bugs _for no good reason_ (ie. `angular.module('mod',[])` will clobber any existing modules named `mod` without warning).
