### ISSUE TITLE
Need to rename services based on convention

### ISSUE THREAD

**Issue by ltvan** [olov/ng-annotate#249]
I'm working on a project which the service proxy is generated with the name like this: `abp.services.app.serviceName' 
http://aspnetboilerplate.com/Pages/Documents/Dynamic-Web-API#DocAngularSupport

Currently I'm using a little hack:
```javascript
var ngAnnotatePlugin = {
  init: function (ctx) {
    ctx.rename = {
      get: function (name) {
        if (/AppService$/.test(name)) {
          return 'abp.services.app.' + name.replace('AppService', '')
        }
        return name
      }
    }
  },
  match: function (node) {
  }
}
```

I'm looking for the ability to pass a callback/plugin to rename services.

Thanks.

**Comment by ltvan** [comment]
Or, something like this is more convenient if we have some services which does not follow any convention:

```javascript
/* @ngInject { userService: 'abp.services.app.user', something:'some-thing' } */
```

**Comment by olov** [comment]
#245
