### ISSUE TITLE
source code contain like `console.log(011)` will get wrong

### ISSUE THREAD

**Issue by zhangsanshi** [olov/ng-annotate#255]
The source code is contain `console.log(011)`
The error is
`error: couldn't process source due to parse error`
Then I remove it, It work.

**Comment by omsmith** [comment]
Are you trying to use an octal literal there? It would be swell if the source parser supported that I suppose, but if you're not actually trying to use octals (the leading `0`), then just fix up your integer.

**Comment by zhangsanshi** [comment]
you are right.
