### ISSUE TITLE
grunt build

### ISSUE THREAD

**Issue by Kirthey** [olov/ng-annotate#256]
![image](https://cloud.githubusercontent.com/assets/23513480/20698208/5498849c-b63a-11e6-9f56-6a1beb3d00fd.png)

why I couldn't build grunt ?

**Comment by omsmith** [comment]
Seems to have no relation to ng-annotate, which does not make use of Grunt.

**Comment by Kirthey** [comment]
![image](https://cloud.githubusercontent.com/assets/23513480/20698483/43296cc4-b63c-11e6-86d1-0aa417c59347.png)

**Comment by omsmith** [comment]
What is that screenshot meant to convey?

**Comment by Kirthey** [comment]
relation to ng-annotate

**Comment by omsmith** [comment]
It seems you've installed ng-annotate successfully, and shown it has no dependency on Grunt?

**Comment by Kirthey** [comment]
Is it need to install something if no dependency on Grunt?
Thank You

**Comment by omsmith** [comment]
I'm sorry, still don't know why you believe ng-annotate would be effecting the outcome if `grunt build`. Can you explain why you think that and thus decided to ask here?

**Comment by Kirthey** [comment]
My problem in ionic app is the image couldn't appear in the real android device but the image can view in the web browser when I run "ionic serve".
I don't know how to add image correctly to view in the real android device?
I got set database in FileZilla and get the link edit the "json" file still the image couldn't appear.
Any solution?

**Comment by omsmith** [comment]
Sounds like you might want to ask the Ionic folk? Certainly not here...

Good luck

**Comment by Kirthey** [comment]
Thank you.
