### ISSUE TITLE
error: couldn't process source due to parse error Unexpected token

### ISSUE THREAD

**Issue by AlienHu** [olov/ng-annotate#264]
Hi , I'm using the  `"gulp-ng-annotate": "^2.1.0"` , I'm trying to use the `async`  `await` in my code , but ng-annotate task is faileing with the below error 

` error: couldn\'t process source due to parse error\nUnexpected token (54:8)',
  plugin: 'gulp-ng-annotate',
  showProperties: true,
  showStack: false,
  __safety: { toString: [Function: bound ] } } 
`

**Comment by olov** [comment]
Hi! ng-annotate is deprecated and closed since two years back, see https://github.com/olov/ng-annotate#deprecation-notice---so-long-and-thanks-for-all-the-bits

**Comment by AlienHu** [comment]
Oh , thanks for writing back @olov , do you suggest any example if i want to replace` gulp-ng-annotate` by `babel-plugin-angularjs-annotate` , it'll be greate if you can help me , thank you

**Comment by mhicauber** [comment]
Hi @AlienHu did you make it work with ng-annotate in the end ?
