### ISSUE TITLE
Running “ngAnnotate:app” (ngAnnotate) task , error: couldn't process source due to parse error

### ISSUE THREAD

**Issue by tikemantns** [olov/ng-annotate#267]
Trying to build angular application cmd: grunt build:prod

Running "ngAnnotate:app" (ngAnnotate) task
Generating ".tmp/concat/scripts/plugins.js" from: ".tmp/concat/scripts/plugins.js"...ERROR
>> error: couldn't process source due to parse error
>> Unexpected token (1275:6)
Warning: Task "ngAnnotate:app" failed. Use --force to continue.

Aborted due to warnings.

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/253
