### ISSUE TITLE
Make it works with Browserify module structure

### ISSUE THREAD

**Issue by jgoux** [olov/ng-annotate#34]
Hi,
firstly, thanks for this awesome tool ! :D
I'm trying to integrate Browserify in my development workflow. It works very well.
Now it's the time to automate some tasks with gulp and ng-annotate, and I have an issue with the minification task.
I structure my code exactly the same way from here : http://benclinkinbeard.com/talks/2014/ng-conf/ (slides 19 to 23)

The problem is that ng-annotate isn't working with this kind of structure, something like this isn't parsed properly : 

``` javascript
// modules/app/frontend/login/login-index.js
'use strict';

module.exports = function($scope) {
        $scope.name = 'guest';
    };
```

The previous controller is called from here : 

``` javascript
// modules/app/frontend/login/index.js
'use strict';

module.exports = angular.module('app.frontend.login', [])
    .config(function($stateProvider) {
        $stateProvider.state('login', {
            url: '/login',
            templateUrl: '/frontend/login/login-index.html',
            controller: 'LoginCtrl'
        });
    })
    .controller('LoginCtrl', require('./login-index'));
```

Is there a solution to make ng-annotate understands this kind of line ?

``` javascript
.controller('LoginCtrl', require('./login-index'));
```

Maybe I'm making something wrong. ^^'

**Comment by mchambaud** [comment]
I've been using this for a very long time but it stopped working when I incorporated tsify in my build. Any idea?
