### ISSUE TITLE
Support explicit @ngNoInject annotation for suppressing false positives

### ISSUE THREAD

**Issue by OverZealous** [olov/ng-annotate#36]
This is great, glad to see such an improvement over ngmin.

One idea I had, which would pretty much allow user-level fixing of any false positives, would be to have a `/* @ngNoInject */` annotation, which would disable automatic injection pretty much in the exact situations `@ngInject` works.

To be clear: I am not having any issue, and this should be a very low priority enhancement, but it might be a nice feature.

**Comment by olov** [comment]
released in 0.15
