### ISSUE TITLE
Provide info about annotated functions

### ISSUE THREAD

**Issue by mgol** [olov/ng-annotate#42]
This is a loose idea but I often add a service to dependencies of another one and then remove its uses but forget to remove the injection. Now, linters often have an option to report unused parameters of functions not only at the end of them, e.g. see:
http://eslint.org/docs/rules/no-unused-vars.html
with `{"args": "all"}` but then I'd have lots of false positives since in case of event handlers, replace functions on strings etc. we're sometimes interested in a second parameter but the first still has to be there.

Since ng-annotate already figures out which functions need to be annotated, I wonder if it was possible to pass this info along in some ways so that it'd be possible to check for unused injections in outside projects.

Or maybe ng-annotate could do this checking on its own? It rarely makes sense to inject components that aren't used in the code after all...

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
