### ISSUE TITLE
Support referenced function declaration

### ISSUE THREAD

**Issue by toddmotto** [olov/ng-annotate#57]
A common pattern a lot of Angular developers I know (myself included) utilise a pattern like this:

``` js
function SomeCtrl () {

}
angular
  .module('app', [])
  .controller('SomeCtrl', SomeCtrl);
```

Currently, to make this work we have to do:

``` js
// @ngInject
function SomeCtrl () {

}
angular
  .module('app', [])
  .controller('SomeCtrl', SomeCtrl);
```

What would the implications be for getting this working with `ng-annotate` without using an `/** @ngInject */` comment? As the method above becomes more popular, I think one of the main downsides to adoption are having to use the comment - is there a way `ng-annotate` can lookup the function based on it's name based on the scope?

**Comment by olov** [comment]
@cherrydev if a duplicate array is created then it's a bug. Can you try with 0.14.1 and file an issue if the problem remains?

**Comment by cherrydev** [comment]
Sorry I never followed up, it's still a problem as of 0.15.4, so I'll file a bug.
