### ISSUE TITLE
Support ES6 syntax

### ISSUE THREAD

**Issue by jonrimmer** [olov/ng-annotate#64]
Using ES6 arrow functions causes parse errors in ng-annotate.

Running ng-annotate after transpilation is not possible due to Traceur removing comments, meaning explicit ```@ngAnnotate``` markers go missing.

**Comment by olov** [comment]
Please check out the proposal in https://github.com/olov/ng-annotate/issues/124#issuecomment-68484704 where a `"use strict"`-like `"ngInject"` string literal would be used for ES6 constructors. Feedback welcome in #124 or here!

**Comment by rootical** [comment]
Thanks for you work! Sorry if it's wrong place to ask.
Spent a few hours trying to make ng-annotate working with es6ify (traceur) output. Without success. I have the latest version of ng-annotate.
Please provide correct syntax to use with es6 classes and the real state of – searching through various issues didn't left any clear vision of how to do that.

**Comment by olov** [comment]
@rootical use `"ngInject";` inside of ES6 functions that you want to have annotated. The ES5-output from Babel will preserve these strings and you can then run them through ng-annotate. I'll add a section about this to the README eventually.

**Comment by mithun-daa** [comment]
@olov That only works on `functions` right? not `classes`?

**Comment by olov** [comment]
@mithun-daa For classes: `class MyCtrl { constructor($a, $b) { "ngInject"; ... } }`

**Comment by JonRimmer** [comment]
Babel will actually preserve comments as well, as long as you have the "compact" option set to "false". I am using ```/* @ngInject */``` annotations on all my ES6 controller functions and classes.

Unless you have very good reasons to keep using Traceur, I recommend switching to Babel. It's has far better support, documentation and configurability.

**Comment by mithun-daa** [comment]
:+1:

**Comment by rootical** [comment]
@olov , @JonRimmer guys, please clarify it a bit. I was able to successfully ng-annotate ``class``es with traceur using  this way ``class MyCtrl { constructor($a, $b) { "ngInject"; ... } }``. 

After switching to babel, I try to use it along with ``browserify-ngannotate`` in a gulp task basically the same way as before with traceur:

```javascript
  bro = browserify('./client/app/app.js', {debug: true});
  bro.transform(babelify.configure({
    compact: true,
    comments: true
  }));
  bro.transform(ngAnnotate);
```

Nothing seems to be ng-annotated. I've also tried to do ``/* @ngInject */`` instead of ``"ngInject";`` with no luck. Am I missing something?

**Comment by rootical** [comment]
Duck debugging helped, that's how it works with babel:

```javascript
/* @ngInject */
class MyCtrl { constructor($a, $b) { ... } }
```

Thanks

**Comment by olov** [comment]
@rootical thanks for reporting, `"ngInject";` not working turns out to be a bug in Babel, which doesn't preserve directive prologues (see https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=class%20MyCtrl%20%7B%20constructor(a)%20%7B%20%22use%20strict%22%3B%20foo%20%7D%20%7D). I'm filing a bug!

**Comment by olov** [comment]
FYI, Babel 4.7.4 and newer supports directive prologues properly so `"ngInject";` will work fine with it

**Comment by olov** [comment]
I'm about to release ng-annotate 1.0 soon and with it I'll close this issue. I'll add proper documentation to the README of how to deal with ES6 and TypeScript, i.e. run ng-annotate on the transpiled output and use `"ngInject";` (preferred) or `/*@ngInject*/` (more fragile to transpiler changes). ng-annotate supporting ES6 (ESxy) code directly could happen in the future if a contributor stepping up.

**Comment by natefaubion** [comment]
A couple of other points wrt to using ngAnnotate on the output of Babel ES6 modules. Babel will transpile an Angular import like so:

```js
import angular from 'angular'
angular.module(...)
```
```js
var _angular = require('angular');
var _angular2 = _interopRequireDefault(_angular);
_angular2['default'].module(...)
```

Which breaks all the usual auto-detection. Would it be possible to configure detection for the `angular.module` as well?

**Comment by olov** [comment]
Check out our `regexp` option https://github.com/olov/ng-annotate#declaration-forms. You case use that to match `[regexp].controller` and so on. The default regexp is `^[a-zA-Z0-9_\$\.\s]+$` which matches things like `myMod` or `myMod.foo`.

As an example (from the README), `--regexp "^require(.*)$"` will work properly for `require('app-module').controller(..)`. In your case, perhaps try `--regexp "angular.*\.module(.*)$"` (not tested).

**Comment by olov** [comment]
1.0.0 is out so closing this because https://github.com/olov/ng-annotate/issues/64#issuecomment-78462297

**Comment by breandr** [comment]
@natefaubion what did you end up doing? You should be able to call ng-annotate before babel.

**Comment by natefaubion** [comment]
@breandr I ended up not importing angular directly (but a util lib instead), and then writing a plugin to match the `(0, foo.bar)(...)` syntax babel emits for imports. I had to fiddle around with `$chained` and `$methodName` (which ngAnnotate uses internally to identify nodes) to get it to work though. The plugin API could use a little love, but maybe I'm not using it correctly.

```js
function NgAnnotateBabelPlugin() {
  var ngProps = ['directive', 'controller', 'config', 'run', 'provider',
                 'service', 'factory', 'filter', 'animation']

  this.init = _.noop
  this.match = function(node) {
    if (node.type === 'CallExpression' &&
        node.callee.type === 'SequenceExpression' &&
        node.callee.expressions[0].type === 'Literal' &&
        node.callee.expressions[0].value === 0 &&
        node.callee.expressions[1].type === 'MemberExpression' &&
        _.contains(ngProps, node.callee.expressions[1].property.name)) {

      return node.arguments.filter(function(arg) {
        if (arg.type === 'FunctionExpression') {
          arg.$chained = 4 // Regular chain
          arg.$methodName = node.callee.expressions[1].property.name
          return true
        }
      })
    }
  }
}
```
```js
import { directive } from '...'

export default directive('foo', () => { ... })
```

**Comment by pmowrer** [comment]
It's a bit ironic that one of Babel's selling points is clearer transpiled source, yet it doesn't work out of the box with ng-annotate, unlike Traceur.

@olov Thanks for the regex, that works (at least for our purposes)! I've modified it the following way for safety: `angular.*?\.module\(.*?\)$`

**Comment by e-cloud** [comment]
@pmowrer just find out, here is a more reasonable one: `angular.*?\\.module(.*?)$`
