### ISSUE TITLE
Release 1.0.0?

### ISSUE THREAD

**Issue by mzgol** [olov/ng-annotate#77]
npm moves into the full-semver direction and in semver anything `<1.0.0` is considered unstable, backwards incompatible changes can occur at any time. While many packages hold a convention to break compat only in minor releases before `1.0.0`, this is not mandatory per spec and that's one reason why the caret operator (`^`) in the upcoming npm 2.0.0 will no longer match newer patch releases for packages with numbers `0.x.y`; e.g. `"ng-annotate": "^0.9.9"` will match only `0.9.9`.

Now, [grunt-ng-annotate](https://github.com/mzgol/grunt-ng-annotate) uses `~0.9.9` but, for example, [gulp-ng-annotate](https://github.com/Kagami/gulp-ng-annotate) uses `^0.9.9` so soon npm users will stop getting patch updates when using that plugin. npm by default uses the caret operator now so more `ng-annotate` dependents may be affected.

Perhaps it's better to follow semver here and use versions `1.0.0` and newer since `ng-annotate` is a maintained, tested software with lots of dependents? What do you think?

(I'm waiting with `grunt-ng-annotate` `1.0.0` for `ng-annotate` so that I don't declare a Grunt plugin stable while it relies on a formally unstable package)

**Comment by olov** [comment]
Unless something unexpected happens next release will be 1.0. It should be out fairly soon (pending feedback from @smrq on a code question)!

**Comment by vatula** [comment]
@olov is it possible to checkout 1.0 branch somehow for testing purposes?

**Comment by olov** [comment]
@vatula just checkout master

**Comment by olov** [comment]
Fixed in 1.0.0

;)
