### ISSUE TITLE
Support combining with preexisting sourcemaps

### ISSUE THREAD

**Issue by olov** [olov/ng-annotate#79]
See https://github.com/olov/ng-annotate/issues/75#issuecomment-55643129

+@smrq

**Comment by mzgol** [comment]
How is this feature supposed to work? I have files generated by babel with inline sourcemaps and after runnning the output via ng-annotate with options:
```js
{ add: true,
  remove: false,
  single_quotes: true,
  sourcemap: 
   { inline: true,
     inFile: '../../processed-pre-ng-annotate/modules/init.js' } }
```
(the source file is at `app/.tmp/processed-pre-ng-annotate/modules/init.js`) to a destination `app/.tmp/processed/modules/init.js` Chrome still shows the sourcemap points to the file from `processed-pre-ng-annotate` and not the original source file, `app/modules/init.js`.

**Comment by mzgol** [comment]
I mean, what I get from ng-annotate is an object with the following value for the `map` property:
```json
{
    "version": 3,
    "sources": ["../../processed-pre-ng-annotate/modules/init.js"],
    "names": [],
    "mappings": "some mappings",
    "sourcesContent": ["source for the file '../../processed-pre-ng-annotate/modules/init.js'"]
};
```
i.e. both the `sourcesContent` and the `sources` array point to the intermediate file, not the first one that's passed to babel.

**Comment by mzgol** [comment]
It does work for me when I invoke `ng-annotate` from a command line, as a binary but doesn't work as an npm module. In the latter case ng-annotate doesn't know the source file but only its contents, I thought that's what the `inFile` option is for, isn't it?

**Comment by mzgol** [comment]
I think I found the issue: #161.
