### ISSUE TITLE
Define the $inject property in an existing line

### ISSUE THREAD

**Issue by mgol** [olov/ng-annotate#81]
Currently, ng-annotate *mostly* preserves lines and columns, making it easy to use during debugging even without relying on source maps.

Unfortunately, annotating via the `$inject` property breaks that invariant as shown in an example from issue #63.

Would it be possible to "append" the definition to an existing line so the invariant can be preserved in all cases again?

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245
