### ISSUE TITLE
False matches on .decorator methods

### ISSUE THREAD

**Issue by schmod** [olov/ng-annotate#82]
Currently, ng-annotate is aggressively annotating functions with `.decorator()` methods.

Specifically, ui-router's [`$stateProvider.decorator()`](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider) method does **not** use DI injections, and breaks if ngAnnotate processes a file that calls it:
#### Original:

``` js
$stateProvider.decorator('parent', function (state, parentFn) {
  doStuff();
});
```
#### After ng-annotate:

``` js
$stateProvider.decorator('parent', ["state", "parentFn", function (state, parentFn) {
  doStuff();
}]);
```

Given that ui-router does not expect an array to be passed into this function, any code that calls `$stateProvider.decorator()` will break if it's processed by ngAnnotate.

Given that `decorator` is potentially a rather generic name, ng-annotate needs to be a lot less aggressive when matching some of these methods.

**Comment by fabricioflores** [comment]
Hi. I'm using 0.15.4 version and gulp-ng-annotate@0.5.2 and I still have this issue...

**Comment by olov** [comment]
@fabricioflores that's weird. The example given in this issue does not get annotated any longer and we have a test case protecting it in the test suite. Can you open up a new issue and provide a minimal input and output? Please run it using the command-line `ng-annotate` directly (`npm install -g ng-annotate` and then `ng-annotate -a example.js`). Thanks.

**Comment by tkhelifiT** [comment]
I can confirm. ng-annotate 0.15.4 is working properly on ui-router's $stateProvider.decorator() method. Verify if your grunt-ng-annotate or gulp-ng-annotate is using the latest version of ng-annotate!!!
